"""initial migration

Revision ID: 387644c3935a
Revises: e0d7ccdddf60
Create Date: 2018-06-26 17:22:17.345000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387644c3935a'
down_revision = 'e0d7ccdddf60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('img1_url', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('img2_url', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('img3_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'img3_url')
    op.drop_column('posts', 'img2_url')
    op.drop_column('posts', 'img1_url')
    # ### end Alembic commands ###
